---
title: "Intro to Linux: Virtual Machine Setup"
format:
    pdf:
        toc: true
        number-sections: true
        colorlinks: true
        output-file: "Lab 1 - Virtual Machine Setup.pdf"
---


# Flavors of Linux

For this course it is recommended that you use Mint or Ubuntu, although there are many more flavors of Linux available. Below is a very short list of the distros that most of you will either use or be familiar with.

1. Ubuntu is designed with beginners in mind. It is a general purpose distro with both server and desktop environments. It is also the most popular distribution.

2. Linux mint is based on Ubuntu and is good for beginners who are switching from windows. This is because it is designed to be familiar for
windows users.

3. Debian is one of the oldest distros and is typically used where stability is paramount. It is used by experienced users and is popular for servers and mission critical environments.

4. Arch linux is used by advanced users for whom customization and minimalist systems are important. Users of this system typically want to be involved in manually setting up everything on the computer.

5. Kali linux is based on debian and is used by cyber security professionals. This is because it comes with multiple tools for penetration testing, forensics and security research

6. Raspbian is a version of linux designed to work on raspberry pis. The focus of this distro is being light weight (i.e. not taking up a lot of space), and yet work fast with the limited hardware resources one might find on a microcomputer like a raspberry pi


# Virtualization Software

In order to use a completely different OS on your computer without significantly affecting it, we are going to use virtualization. **Virtualization** allows us to install and use multiple versions of different computers independent of the physical computer we actually have. It allows us to test out different software with the security of knowing we cannot affect our host computer and can even revert to an older version of the software we are trying. The cost of virtualization is that you typically have to be comfortable with running the computer with reduced resources i.e. it doesn’t have access to all your memory or processors.

## Download Virtual Box and Install


1. Download Virtual Box from Oracle by visiting [https://www.virtualbox.org/wiki/Downloads](https://www.virtualbox.org/wiki/Downloads){target="_blank"} . Click the appropriate download link for your system.

2. Install Virtual Box. 


:::{.callout-tip}
# Windows Host Tip

Note that when installing on windows, you might get an error concerning needing to install Visual c++ 2019. You can resolve this error by visiting [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) and downloading the latest X64 version of Microsoft Visual C++. Alternatively, here is a direct download link for convenience [https://aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe). Also, if you received this error, once VirtualBox has been installed, restart your computer.
:::

:::{.callout-tip}
# Mac Host Tip

If you have a mac with homebrew, you can run the following command to both download and install:

```sh
brew install --cask virtualbox
```
:::

:::{.callout-warning}
# Apple Silicon (M-series) Macs

VirtualBox's support for Apple Silicon (M1/M2/M3/M4/M5 Macs) has historically been unreliable compared to its support for Intel-based machines, so you may run into crashes, stability issues, or missing features. If you run into problems, [UTM](https://mac.getutm.app/) is a free alternative that is generally better supported on Apple Silicon and may be worth trying instead.

**However**, the rest of this course's instructions (including later labs, such as Network Setup) are written and tested against VirtualBox specifically. We have not tested those instructions against UTM, so menu names, settings locations, and even some underlying behavior (e.g. bridged networking) may not match what's described. If you choose UTM, expect to do some translation on your own, and flag any issues you run into so we can improve these instructions.
:::


:::{.callout-tip}
# Linux Host Tip

If you are a Linux user, you can download and install virtual box using the following commands.

```sh
sudo apt update
sudo apt install virtualbox virtualbox-qt
```
:::




# Downloading an ISO

In this class we support Linux Mint and Ubuntu Desktop for the Windows host users and Ubuntu Server for the Mac host users. You are welcome to use a distribution outside of these, however, you may be alone when it comes to troubleshooting. 

People that typically use Windows will find Linux Mint to be a comfortable place. 

Ubuntu server is being used for users with Mac hosts as it currently (year of 2025) the most easily accessible ARM64 based distribution. Macs with the m-series chips have ARM64 architecture. 

1. Download the appropriate image for your virtual machine based on your host:

    - If you have an **x86-64/amd64** based machine (most Windows machines and Intel based macs):
        - [Linux Mint](https://www.linuxmint.com/download.php)
            - note that the `xfce` edition is recommended for virtual machines
        - [Ubuntu Desktop](https://ubuntu.com/download/desktop)

    - If you have an **arm64** based machine (m-series Macs and very few Windows machines):
        - [Ubuntu Server](https://ubuntu.com/download/server/arm)

    - You are welcome to use any other Linux distro, links not provided, troublshooting and instructions not provided.

2. Once you have downloaded the `.iso` file, move the file to the folder you have created for this course on your computer so you can easily find it when you need it later.


# Installing the OS on Virtual Box

This section of the instructions apply regardless of the flavor of Linux you chose.

1. Create a new VM in Virtual Box by clicking NEW.

2. Give it a name of your choosing. You might do something like the name of this class. This is just how VirtualBox will label it for your own referencing purposes.

3. For the `Folder` option, you can leave the default selected folder. It is most likely something along the lines of `.../VirtualBox VMs`.

4. For the` ISO Image` option, select the .iso file you downloaded in the previous section of these instructions. You may need to click "other" in the dropdown to browse for it.

6. Skip the unattended install by checking the box to skip it.

7. When prompted for `base memory`, it is recommended that you allocate enough for the VM to run a full desktop environment comfortably while leaving enough for your host OS and other applications.

    - If you have 8 GB of RAM, consider allowing 2-3 GB for the virtual machine.
    - If you have 16 GB of RAM, consider allowing 4-6 GB for the virtual machine.
    - If you have 32 GB of RAM or more, consider allowing 8 GB for the virtual machine.

   This is only setting the max it can use on your machine, so feel free to adjust up or down, but allocating too much may start slowing down the host.

8. When prompted about the `processors`, it is recommended you give it at least 2, and 4 if your machine's CPU has enough cores to spare (most machines sold in the last several years do).

9. When prompted about the `Hard Disk`, make it sufficient in size, say 100 GB for storage. **Do not** pre-allocate the storage.

10. Click "Finish" to finish this portion of the setup. This does not setup the machine. Just prepares it for setup.


# Modify VirtualBox Settings

Now that the machine exists inside virtual box, it is recommended you complete the following.

1. Bidirectional Clipboard and Drag and Drop Support

    a. Select the machine on the left hand side of the window.
    b. Select `Settings` near the top of the window.
    c. Go to `General`.
    d. Go to `Advanced`.
    e. Set `shared clipboard` to `bidirectional`.
    f. Set `drag'n'drop` to `bidirectional`.
    g. Click `OK` to save.

    Note: We've had mixed results with the clipboard and drag and drop actually working.

2. Network Connectivity

    a. Select the machine on the left hand side of the window.
    b. Select `Settings` near the top of the window.
    c. Go to `Network`.
    d. Under the `Attached To:` option, choose `Bridged Adapter` instead of `NAT`.
    e. Under the `Name:` option, choose the normal connection you use, probably your Wi-fi connection
        - On windows, you might only have one option (your Wi-Fi)
        - On macs, it is most likely en0: Wi-Fi

    Note: NAT stands for Network Address Translation. If this is the setting, then virtual machine and host machine will share an IP address when communicating with the outside world. The Bridged Adapter allows the virtual machine to receive it's own ip address when communicating with the outside world.


# Installing and Booting the VM

Boot the VM by selecting it in the left navigation and clicking "Start".

For this step, the instructions will be different depending on the flavor of Linux you chose, be sure to scroll to the appropriate section for your VM's operating system.

:::{.callout-note}
# What About Partitioning?

During installation you may notice a manual partitioning option (e.g. `Something Else` in Mint) instead of the recommended guided option. Partitioning lets you reserve specific amounts of disk space for different parts of the filesystem, such as a separate `/home` partition, which historically made it easier to reinstall or upgrade the OS without losing personal files.

Partitioning is less critical today thanks to cheap storage and modern backup/snapshot tools, but it's still a useful concept to understand as a computer science student since you won't always be working with the latest hardware or tooling. If you want to experiment, choose the manual partitioning option and create separate partitions for `/boot`, swap, `/` (root), and `/home` — just be sure you're partitioning the virtual disk you created for this VM, not your host machine's drive.

For this course, using the guided/automatic option is perfectly fine and recommended.
:::

## For Mint

For Mint, you will be presented with a GUI that should be simple to step through. You'll see a disk in the top left corner labeled "Install Linux Mint". Double click it to start. Some notes for your install follow:

1. Language: Choose English

2. Multimedia Codecs: No (these will not be necessary)

3. Now you'll be presented with the options to `Erase Disk and Install Linux Mint` or `Something Else`. 

    Choosing `Erase Disk and Install Linux Mint` is the simplest option and is recommended for this course. This will not erase anything on your host machine since we are doing this inside of virtualization software.

    If you wanted to be a bit more specific about the partitions that get created, you can choose `Something Else` instead. See the "What About Partitioning?" callout above for guidance.

    Once you've made your selection, click "Install Now"

4. Time zone: Chicago

5. If you chose `Something Else`, use Mint's on-screen partition editor to create your partitions, then continue to step 6. If you chose `Erase Disk and Install Linux Mint`, move straight to step 6.

6. Now you'll be asked for some information such as username, computer name, and password. Make a username and password that you'll remember. You do not need to encrypt your home folder, but could if you wanted to.

## For Ubuntu Desktop

Ubuntu desktop will present you with a step by step installation process. Follow this process. If you are interested in a custom partition, see the "What About Partitioning?" callout above, otherwise use the default partitioning.

## For Ubuntu Server ARM
This could take some time, so it is not recommended that you update when prompted during the install if you are short on time.

1. When prompted, select "Try to Install Ubuntu".

3. The install will present lots of options that you can choose to customize. At some point it will ask for a username and password, be sure you remember it.

4. Once it is installed it will prompt to reboot. 

5. After rebooting it'll ask you to login with the username and password once you reboot.

6. Setting Up the GUI. Note that there will be gui based software that is used in this course, so it is recommended that you setup the gui.

    a. Run the following two commands separately

    ```bash
    sudo apt update
    ```

    ```bash
    sudo apt install ubuntu-desktop
    ```

    b. Once it is done, turn the machine off by closing the window and selecting the option to turn the machine off. 
    
    c. Start the machine and log back in. There should be a GUI at this point.


# Shared Folders

A **shared folder** lets you exchange files between your host machine and the VM directly through the filesystem, without needing FTP, SSH, or a USB drive. This is convenient for editing code in a host-side editor, copying over screenshots, or moving files you downloaded on the host into the VM.

:::{.callout-warning}
# VirtualBox-Specific Feature

Shared folders rely on VirtualBox's own `vboxsf` filesystem, which is provided by VirtualBox Guest Additions. If you are using UTM instead of VirtualBox (see the Apple Silicon callout earlier in this lab), file sharing works differently (UTM uses `virtfs`/9p) and the steps below will not apply — consult UTM's own documentation instead.
:::

## Install Guest Additions

Shared folders will not work until **Guest Additions** are installed inside the guest OS. Boot your VM (see "Installing and Booting the VM" above) and run the following from a terminal inside the guest:

```sh
sudo apt update
sudo apt install virtualbox-guest-utils virtualbox-guest-x11
```

Reboot the VM once installation finishes.

:::{.callout-note}
# Already Have Guest Additions?

Some ISOs (particularly Ubuntu Desktop) may already include a working set of Guest Additions. If the shared folder steps below don't work as expected, installing/reinstalling with the commands above is a safe first troubleshooting step.
:::

## Add the Shared Folder in VirtualBox

1. **Create or choose a host folder.** On your host machine, create a folder (or pick an existing one) that you want the VM to be able to access.

2. **Power off the VM**, then select it in the VirtualBox main window and click **Settings**.

3. Go to the **Shared Folders** section.

4. Click the **+** button to add a new shared folder.

5. Configure the new folder:

    | Field | What to Enter |
    |---|---|
    | **Folder Path** | Browse to (or type) the host folder from step 1 |
    | **Folder Name** | The name the guest OS will see — this does not have to match the host folder's name |
    | **Read-only** | Check this if the VM should not be able to modify files in the folder |
    | **Auto-mount** | Check this so the folder mounts automatically every time the VM starts, instead of requiring a manual `mount` command each session |
    | **Mount Point** | Leave blank if Auto-mount is checked; only needed on very old VirtualBox versions |

6. Click **OK**, then start the VM.

## Accessing the Shared Folder in the Guest

:::{.callout-important}
# Add Yourself to the `vboxsf` Group

Even with Guest Additions installed, a regular user cannot access shared folders until added to the `vboxsf` group:

```sh
sudo usermod -aG vboxsf $USER
```

**Log out and back in** (or reboot the VM) for the new group membership to take effect. This is the single most common reason a shared folder appears to "not work."
:::

If you checked **Auto-mount**, the folder will appear automatically at:

```
/media/sf_<FolderName>
```

where `<FolderName>` is whatever you entered in the **Folder Name** field above.

If you did not enable Auto-mount, mount it manually with:

```sh
sudo mount -t vboxsf FolderName /path/to/mount/point
```

replacing `FolderName` with the name from the VirtualBox settings, and `/path/to/mount/point` with an existing directory on the guest (e.g. `~/shared`).

:::{.callout-tip}
# Verifying It Worked

Create a test file on the host side of the shared folder, then check that it appears on the guest at the mount point (and vice versa). If the folder is empty or missing, double check the group membership step above and confirm you rebooted or logged out/in afterward.
:::







