---
title: "Timing Covert Channel Lab"
date: "September 20, 2025"
title-block-banner: "#002f8b"
toc: true
toc-depth: 2
number-sections: true
format:
  pdf:
    code-copy: false
    code-fold: true
jupyter: python3
---

In the last lecture, you covered different ways that someone might set
up and take advantage of a Covert Channel. In the last lab, you set up
one such Storage covert channel using the file permissions of an FTP
server.

In this lab, we shall set up a Timing Covert Channel. We will set up a
server that will transmit text overtly, but transmit a covert message
hidden in the timings between each successive character of the overt
message.

As an example, a delay of 0.025s between parts of the message could be
translated to a 0 while a delay of 0.1s can be translated as a 1.

In order to transfer a long covert message, we will need a much longer
overt message. Using the suggestion above, transmitting a single covert
character (7 or 8 bits) would require the transmission of 8 or 9
characters. As mentioned earlier, this isn't too unreasonable because
Covert channels are typically low bandwidth (i.e. can only realistically
send small messages).

To end the message we have a couple of options to consider. We could
just repeat the covert message over and over and trust the recipient to
know when they have received the entire message. However, this would
make our channel easy to notice and analyse. A more surreptitious option
would be to add a special tag at the end of our covert message to
signify that the hidden message has been received in its
entirety...perhaps the string "EOF"

# Setting up the server

## Sending a basic message {#sec-basicserver}

Let's create a basic TCP server using Go's net library. Our server will
accept connections from any clients on a specified port, listen to any
incoming messages across that connection, and then echo the message back
to the client.

```go
package main

/* 
*   we'll need bufio for input/output, fmt for printing messages, net for
*   networking functions, and os to help us exit the program if things go 
*   south. 
*/
import (
	"bufio"
	"fmt"
	"net"
	"os"
)

// set up some constants to make your server easier to tweak
const (
    address = ""	// allow all connections. Use 127.0.0.1 if you
			// only want local connections.
    port = "1337"	// the port we will be using
)


func main() {
	// Start listening on TCP to specified port
	listener, err := net.Listen("tcp", address + ":" + port)

	// if there is an error in starting the server, end the program
	// with an appropriate error message.
	if err != nil {
		fmt.Println("Error starting server:", err)
		os.Exit(1)
	}

	// use the defer functionality to close the listener whenever
	// main() is done.
	defer listener.Close()

	fmt.Printf("Server listening on %s:%s", address, port)

	// start an infinite loop that will handle all incoming
	// connections.
	for {
		// Accept new connections
		conn, err := listener.Accept()
	
		/*  
		*   if something goes wrong with the incoming connection, 
		*   print out the error, and continue to the next
		*   iteration/connection. 
		*/
		if err != nil {
			fmt.Println("Error accepting connection:", err)
			continue
		}

		/* 
		*   However, if connection is good, print out a message,
		*   and then call a goroutine (thread) with the custom 
		*   function handleConnection() and the connection conn
		*/
		fmt.Println("New client connected!")

		go handleConnection(conn)
	}
}

// custom function to be executed with each connection received.
func handleConnection(conn net.Conn) {

	// use the defer functionality to ensure that the connection is
	// closed at the end of the function no matter what.
	defer conn.Close()

	// prepare to read information from the connection.
	reader := bufio.NewReader(conn)

	/*
	*    An infinite loop to read whatever string is sent from the
	*    client, print it to the screen, and send a copy of that same
	*    message back to the client.
	*/
	for {
		// Read data from client
		message, err := reader.ReadString('\n')
		
		// if there is an error, log it, and then end the
		// function
		if err != nil {
			fmt.Println("Client disconnected.")
			return
		}
		fmt.Print("Message received:", message)

		// Send a response back
		conn.Write([]byte("You said: " + message))
	}
}

```

:::{.callout-tip}
If you haven't done any socket programming before, this is a good place
to stop and test your server. Its always fun to see how your code could
work over a network.

Later on in this lab, we'll design a programmatic client that will
connect to our server. But you don't need one for now. You can use
built-in tools in the terminal that allow you to connect to a
client/port.

1. Using **telnet**
```sh
telnet localhost 1337	# general form is telnet server_ip server_port
```
Telnet is used for plain text communication and is unencrypted so don't
use it for sensitive data.

2. Using **netcat**
```sh
nc localhost 1337
```
Hit `Ctrl + C` or type `exit` to exit. Netcat is used to test and debug
network services.

You can also share your server's ip address with your
deskmates/groupmates to try and connect to each other's servers. If so,
connect to their server by tweaking your commands above
```sh
telnet ip.ad.re.ss 1337	# OR
nc ip.ad.re.ss 1337
```
where `ip.ad.re.ss` is your groupmate's ip adress.
:::

## Sending an Overt message

The code above is a very simple server example. We need to tweak it in a
few ways on our way to setting up our covert channel.

1. We should stop it from reading any incoming messages from the client
   (because all it should do is send messages), and
2. We need to send our message one character at a time with a delay
   between each character. 

In order to do this, we shall have to make a few changes to our
code above starting with importing the `time` package for its `Sleep`
function.

```go
import (
	"bufio"
	"fmt"
	"net"
	"os"
	"time"
)
```

To make our code easier to adjust, we should probably put some time
constants at the top of our code too.

```go
const (
    address = ""	// allow all connections. Use 127.0.0.1 if you
			// only want local connections.
    port = "1337"	// the port we will be using
    zero = 25		// How many milliseconds to wait for a zero
    one	= 100		// How many milliseconds to wait for a one
)
```

To capture everything we want to do with a connection, it'll probably be
cleaner and easier to use a completely different function instead of
`handleConnection` to deal with sending an overt message.

```go
func sendMessage(message string, conn net.Conn) {
    defer conn.Close()	// make sure to close connection at end of function

    for i, ch := range message {
         _, err := conn.Write([]byte(string(ch)))

        // if there is an error while writing, log it and end function
        if err != nil {
	    fmt.Println("Error writing to client:", err)
            return
        }

        /*
        * Otherwise, wait for a "zero" or "one" based on whether the
        * index is even or odd. Of course this is just for
        * demonstration purposes and will have to be changed when we want
        * to actually use our covert channel.
        */
        if i % 2 == 0 {
            time.Sleep(one * time.Millisecond)
        } else {
            time.Sleep(zero * time.Millisecond)
        }
    }
        
    fmt.Println("Overt message sent. Closing connection.")
    return
}
```

To accommodate this new function, we will also need to tweak our `main`
function a little.

```go
...
message := "This is a really message that will be sent a character at a time"
...
// go handleConnection(conn)	// old function call
go sendMessage(message, connn)	// new function call
```

## Creating our covert message

We have most of the components to put our entire code together. However,
we still have the question of how we know whether to transmit a 0 or 1
for our covert message.

To answer that question, we'll need to assemble our covert message and
then convert it to binary. There are multiple ways to do this but one of
them is to **use the `strings` package**.

```go
func getCovert() string {
    covert := "secret" + "EOF"
    var result strings.Builder

    for _, c := range covert {
	result.WriteString(fmt.Sprintf("%08b", c))
    }
    return result.String()
}
```

As an example, if `covert == "ABC"`, then 
`getCovert()` would return  `"010000010100001001000011"`

We now need to make a few tweaks to the `sendMessage` function 

```go
...
covert := getCovert()
...
if covert[i % len(covert)] == '1' {
    time.Sleep(one * time.Millisecond)
} else {
    time.Sleep(zero * time.Millisecond)
}

```

# Setting up the Client

:::{.callout-tip}
Historically, timing has not been super reliable on Windows when running
python scripts. We mention this so that you are not shocked if the
timings are not what you expect when on Windows. We have not yet tried
this with *Go* so you'll be our guinea pigs.
:::

## Receiving a Basic Message
Let's create a basic client using Go's net library. This client should
be able to send and receive messages from our original chat server in
@sec-basicserver

```go
package main

import (
	"bufio"
	"fmt"
	"net"
	"os"
)

func main() {
	// Connect to the TCP server
	conn, err := net.Dial("tcp", "localhost:1337")
	if err != nil {
		fmt.Println("Error connecting:", err)
		os.Exit(1)
	}
	
	// prepare to close the connection when the main function is
	// done.
	defer conn.Close()

	/* This client code will allow you to type out a long message
	*  terminated by "Enter". That message will then be sent to the
	*  server which will read the message, and echo it back to the
	*  client. When received, the client will print the message to
	*  the screen, and then wait for the user to type a new message.
	*/

	fmt.Println("Connected to server. Type a message and press Enter:")

	// Read from stdin and send to server
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		text := scanner.Text()

		// Send to server
		fmt.Fprintf(conn, text+"\n")

		// Read response
		response, err := bufio.NewReader(conn).ReadString('\n')
		if err != nil {
			fmt.Println("Error reading from server:", err)
			break
		}
		fmt.Print("Server replied: " + response)
	}
}

```

## Receiving many small messages

While the behaviour of the code above is adequate for a normal echo
server, it will not suffice for our covert/overt channel transmission
for a couple of reasons.

- Our client should only be receiving a message and not sending one.
- Our client should ideally print out any message or part of the message
  that it receives immediately instead of waiting for the entire message
  (or a line terminated by a newline character) to be received.

```go
// you will need to import "io" to be able to identify an EOF message
// Note that this is different from the literal letters EOF appended to 
// a message.
...
// create a Reader object for the server responses
reader := bufio.NewReader(conn)

// then loop until you get to the end of the message or get an
// error
for {
    r, _, err := reader.ReadRune()

    if err != nil {
        if  err == io.EOF {
            fmt.Println("\nServer closed Connection")
            break
        }
        fmt.Println("\nError reading from server:", err)
        break
    }

    // otherwise print out the rune
    fmt.Printf("%c", r)
}
...
```

## Receiving the covert message

We now need to figure out a way to measure the time between each
received message and interprete that as either a 0 or a 1. To do this,
we'll need to use the `time` library and take multiple time measurements
during our code's execution.

```go
// import the "time" library
...
// create a slice of time.Duration objects so that you can visually
// inspect the times to see if they fall into two or more groupings.
var times []time.Duration
...
// within the for loop getting the message
start := time.Now()
r, _, err := reader.ReadRune()
stop := time.Since(start)
...
// printing out the final slice should allow you to observe the
// durations and identify any details that might help you decipher
// the covert message.
fmt.Println(times)
```

## From times to characters

It should be relatively easy to identify an algorithm to convert the
times from raw times to `1`s or `0`s. Once that has been done, those bit
strings can then be converted to actual characters -- a process you have
already done in an earlier assignment.

:::{.callout-note}
The entire **client** section of this lab has been intentionally vague.
All the parts are included in the section but they are not organized
into a comprehensive solution, and code snippets have been scarce. It
will be up to you to figure out how to arrange them in order to get a
well designed piece of code that will log into the server, receive the
overt message, compile the covert message, and interpret the covert
message. *Good luck*
:::
